---
- name: set OS facts for Ubuntu Trusty derivatives
  set_fact: doublecmd_os_codename=trusty
  when:
  - doublecmd_os_codename in [
      "rosa",
      "rebecca",
      "rafaela",
      "stretch",
      "jessie"
    ]

- name: set OS facts for Ubuntu Xenial derivatives
  set_fact: doublecmd_os_codename=xenial
  when:
  - current_distro in [
      "Linuxmint18",
      "Debian9"
    ]


- name: add double commander ppa
  apt_repository:
    repo: 'ppa:alexx2000/doublecmd'
    codename: "{{ doublecmd_os_codename }}"
    filename: doublecmd
    state: present

- name: update cache
  shell: apt-get update

- name: install double commander
  apt: name=doublecmd-qt state=latest
